import React from 'react';
import Image from 'next/image';
import PromoGrid from './promoGrid';
import PostedPromos from './postedPromos';
import frame16 from "../../../public/assets/images/Rectangle 16.png";
import Link from "next/link";

export const metadata = {
  title: "Promos | SAGU Bubble Tea",
  description: "Generated by Next.js",
};

function Promos() {

  return (
    <div>
      {/* SAGU Club */}
      <section className="flex flex-grow max-w-screen-xl my-10 lg:my-20 px-6 overflow-hidden">
        <div className="flex flex-col items-center gap-10 overflow-auto lg:flex-row">
          <div className="flex flex-col gap-10">
            <h1 className="text-5xl font-medium font-red-hat">
              SAGU Bubble Tea's Club
            </h1>
            <p className="text-2xl sm:text-4xl md:text-2xl">
              Excepteur dolor voluptate aute deserunt magna sunt velit labore
              adipisicing. Lorem amet commodo ea eiusmod enim nostrud tempor
              tempor eiusmod elit et ea sit. Id sint ex est consequat. Aliquip
              id aliquip mollit nisi nulla tempor commodo velit.
            </p>

            <Link href="/menu">
              <button className="h-[40px] w-[159px] overflow-hidden rounded-full bg-customColor text-lg font-semibold text-white duration-300 mb-2 md:mb-0 uppercase hover:drop-shadow-md hover:brightness-90">
                Get a Bubble
              </button>
            </Link>
          </div>

          <Image
            className="flex w-full h-full rounded-lg drop-shadow-lg items-stretch"
            src={frame16}
          />
        </div>
      </section>

      {/* Section Seperator */}
      <hr className="border-t border-solid border-black border-2 my-20" />

      {/* Other Promos */}
      <section className='flex flex-grow max-w-screen-xl my-10 lg:my-20 px-6 overflow-hidden'>
        <PostedPromos />
      </section>
    </div>
  );
}

export default Promos;
