import React from 'react'
import Careers from './CareerLayout';

export const metadata = {
  title: "Careers | SAGU Bubble Tea",
  description: "Generated by Next.js",
};

function careersPage() {
  return (
    <div>
      <Careers />
    </div>
  );
}
export default careersPage;