import Login from "./login-form.js";

export const metadata = {
  title: "Log In | SAGU Bubble Tea",
  description: "Generated by Next.js",
};

function LogIn() {
  return (
    <div className="w-full flex justify-center">
      <section className="w-full max-w-screen-xl mt-10 lg:mt-20 mb-10 px-6">
        <div className="flex flex-col items-center w-full">
          <div className="col-span-12 flex flex-col p-1 justify-center order-last col-start-1 sm:order-none">
            <h1 className="text-2xl sm:text-2xl md:text-2xl font-medium pb-4">
              Login to receive and earn rewards
            </h1>
          </div>
          <div className="col-span-12 flex flex-col p-1 justify-center order-last sm:order-none">
            <div className="box-content rounded-2xl w-[440px] bg-customColor p-2">
              <div class="p-5">
                <Login />
              </div>

              <div className="bottom-0 w-full text-center pb-2">
                Don&apos;t have an account?{" "}
                <a href="/signup" class="hover:text-white">
                  <strong>Sign Up</strong>
                </a>{" "}
                here
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
}

export default LogIn;
