import Signup from "./signup-form.js";

export const metadata = {
  title: "Sign Up | SAGU Bubble Tea",
  description: "Generated by Next.js",
};

function SignUp() {
  return (
    <div className="sidebar mb-5">
      <h2 className="flex py-5 text-4xl text-left font-bold">
        Sign Up to Gain Rewards
      </h2>
      <div className="flex box-content border-radius-[30px] bg-customColor flex-col rounded-2xl ">
        <div class="p-5">
          <Signup />
        </div>

        <div className="text-center mb-5">
          By clicking &quot;Create an Account&quot;, you are agreeing to <a href="/terms-and-conditions" class="hover:underline hover:text-white"><strong>Terms & Conditions</strong></a> and <a href="/privacy-policy" class="hover:underline hover:text-white"><strong>Privacy Policy</strong></a>.
        </div>
      </div>
    </div>
  );
}

export default SignUp;
