
import SignUp from '../signup/page.js'; 
import LogIn from '../login/page.js';
import Profile from './profile.js';


export const metadata = {
    title: "Account | SAGU Bubble Tea",
    description: "Generated by Next.js",
  };

// Things to do : Placement , CSS, picture, information
function Account({userId}){

  //alerts user that they have earned a free boba tea
  // if (userId.points == 10){
  //   alert("Congratulations! You have earned a free boba tea!");
  // }
  
  return(
    <div className='flex-auto'>
      <Profile />
    </div>
  )

}
export default Account;