import React from "react";
import SquarePaymentForm from "./paymentForm.js";
import CheckoutSummary from "./checkoutSummary.js";


export const metadata = {
  title: "Checkout | SAGU Bubble Tea",
  description: "Generated by Next.js",
};

function Checkout() {
  return (
    <div className="flex w-full mt-10 lg:mt-20 mb-10 lg:mb-20 px-6 overflow-hidden">
      <section className="flex flex-col sm:flex-row w-full mt-1 lg:mt-2">
        <div className="grid grid-cols-1 sm:grid-cols-12 gap-6 items-stretch w-full">
          <div className="col-start-1 sm:col-span-4 row-start-1 sm:row-start-1 h-auto">
            <h1 className="text-customColor text-start font-public-sans font-bold text-2xl">
              Checkout
            </h1>
          </div>

          {/* Payment Form w/ Order Summaries */}
          <div className="col-span-12 sm:col-span-8 row-start-2 sm:row-start-2 flex flex-col justify-start">
            <SquarePaymentForm />
          </div>

          <div className="col-span-12 sm:col-span-4 row-start-4 sm:row-start-2 flex flex-col justify-start gap-5">
            <CheckoutSummary />
            
            <button className="h-[50px] self-end overflow-hidden rounded-md bg-[#b7b6f5] text-md font-semibold text-white duration-300 mb-2 md:mb-0 uppercase hover:drop-shadow-md hover:brightness-90 w-full">
              <a href="/cart">Return to Cart</a>
            </button>
          </div>
        </div>
      </section>
    </div>
  );
}

export default Checkout;
