import Categories from "./categories";

export const metadata = {
  title: "Menu | SAGU Bubble Tea",
  description: "Generated by Next.js",
};
  
const MenuPage = () => {

  return (
    <div>
      <Categories/>
    </div>
  )
}

export default MenuPage;