import Image from "next/image";

export const metadata = {
  title: "SAGU Bubble Tea",
  description: "Generated by Next.js",
};

import Feedback from "./feedback/feedback";

import frame27 from "../../public/assets/images/Frame 27.png";
import frame32 from "../../public/assets/images/Frame 32.png";
import frame33 from "../../public/assets/images/Frame 33.png";
import frame34 from "../../public/assets/images/Frame 34.png";
import frame40 from "../../public/assets/images/Frame 40.png";
import Link from "next/link";

function Home() {
  return (
    <div>
      {/* Hero Section */}
      <section className="flex max-w-screen-xl mt-10 lg:mt-20 px-6 overflow-hidden">
        <div className="grid grid-cols-12 grid-rows-1 gap-6 items-stretch w-full">
          <div className="col-span-12 sm:col-span-5 flex flex-col p-1 justify-center order-last sm:order-none">
            <div>
              <h1 className="text-2xl sm:text-4xl md:text-5xl font-medium pb-4">
                Fall season calls for new flavours!
              </h1>
              <p className="text-lg sm:text-2xl md:text-2xl pb-8">
                New season means new flavours. Introducing our new flavours;
                pumpkin spice latte, cinnamon match tea, and chai tea. Hurry
                before they are gone!
              </p>
            </div>
            <Link href="/menu">
              <button className="h-[40px] w-[159px] overflow-hidden rounded-full bg-customColor text-lg font-semibold text-white duration-300 mb-2 md:mb-0 uppercase hover:drop-shadow-md hover:brightness-90">
                Get a Bubble
              </button>
            </Link>
          </div>

          <Image
            className="col-span-12 sm:col-span-6 sm:col-start-7 order-first sm:order-none flex items-stretch drop-shadow-lg object-cover w-full h-full rounded-lg"
            src={frame27}
          />
        </div>
      </section>

      {/* Items Section */}
      <section className="flex flex-col sm:flex-row w-full mt-10 lg:mt-20 px-6">
        <div className="grid grid-cols-1 sm:grid-cols-12  gap-6 items-stretch w-full">
          {/* First Column */}
          <a
            className="flex flex-col col-span-12 sm:col-span-4 p-1 justify-center hover:text-customColor"
            href="./menu"
          >
              <h4 className="text-center text-lg sm:text-xl md:text-2xl font-medium pb-4 whitespace-nowrap truncate">
                Check out our other menu
              </h4>

              <Image
                className="row-start-2 flex items-stretch drop-shadow-lg max-h-[200px] sm:max-h-[368px] object-cover w-full h-full rounded-lg"
                src={frame32}
              />
          </a>

          {/* Second Column */}
          <a
            className="flex flex-col col-span-12 sm:col-span-4 p-1 justify-center hover:text-customColor"
            href="./our-story"
          >
              <h4 className="text-center text-lg sm:text-xl md:text-2xl font-medium pb-4 whitespace-nowrap truncate">
                Learn more about us
              </h4>

              <Image
                className="flex items-stretch drop-shadow-lg max-h-[200px] sm:max-h-[368px] object-cover w-full h-full rounded-lg"
                src={frame33}
              />
          </a>

          {/* Third Column */}
          <a
            className="flex flex-col col-span-12 sm:col-span-4 p-1 justify-center hover:text-customColor"
            href="https://maps.app.goo.gl/fyV5yxF74cKZvym28"
          >
              <h4 className="text-center text-lg sm:text-xl md:text-2xl font-medium pb-4 whitespace-nowrap truncate">
                Come visit us in person!
              </h4>

              <Image
                className="flex items-stretch drop-shadow-lg max-h-[200px] sm:max-h-[368px] object-cover w-full h-full rounded-lg"
                src={frame34}
              />
          </a>
        </div>
      </section>

      {/* Review Section */}
      <section className="flex max-w-screen-xl my-10 lg:my-20 px-6 overflow-hidden">
        <div className="grid grid-cols-12 grid-rows-1 gap-6 items-stretch w-full">
          <Feedback />

          <Image
            className="col-span-12 sm:col-span-3 sm:col-start-10 flex flex-col p-1 justify-center order-last sm:order-none items-stretch drop-shadow-lg object-cover w-full max-h-[200px] sm:max-h-full rounded-lg"
            src={frame40}
          />
        </div>
      </section>
    </div>
  );
}

export default Home;
