export const metadata = {
    title: "SAGU Bubble Tea",
    description: "Generated by Next.js",
  };

function Register() {
    return (
        <div>Register</div>
    );
}

export default Register;